# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildJob
    displayName: 'Build and Push'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'docker-hub'  

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        command: buildAndPush
        containerRegistry: 'docker-hub'
        repository: 'nakulkaushik/myapp'  
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest

    - script: |
        echo "Docker build completed." > $(Build.ArtifactStagingDirectory)/build-summary.txt
      displayName: 'Generate build summary'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Logs'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'build-logs'
        publishLocation: 'Container'

- stage: Test
  displayName: 'Run Tests'
  dependsOn: Build
  jobs:
  - job: RunTests
    displayName: 'Run Unit Tests'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Running dummy tests..."
        echo "Tests passed successfully!" > test-results.log
      displayName: 'Run Mock Tests'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Test Logs'
      inputs:
        PathtoPublish: 'test-results.log'
        ArtifactName: 'test-logs'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  condition: succeeded()  # Only run if tests passed
  jobs:
  - job: DeployJob
    displayName: 'Deploy Docker Image'
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Deploying application..."
        echo "Deploying image: nakulkaushik/myapp:$(tag)"
      displayName: 'Mock Deploy Step'