# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'docker-hub'

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'nakulkaushik/myapp'
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
